services:

  mysql:

    image: mysql:8.0

    container_name: college-mysql

    environment:

      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: college_db

    ports:

      - "3307:3306"

    volumes:

      - mysql_data:/var/lib/mysql

    restart: always

  springboot-app:

    build: .

    container_name: college-app

    ports:

      - "8080:8080"

    depends_on:

      - mysql

    environment:

      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/college_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

    restart: always

volumes:

  mysql_data:
 